### ISSUE TITLE
Event Listener pool configuration cannot target mgmt IP on 1nic BIG-IP

### ISSUE THREAD

**Issue by vtrippel** [F5Networks/f5-telemetry-streaming#1]
**Issue Type:**

- Known Issue

**Summary:**

Single NIC instances of BIG-IP produce an error when creating the pool for TS usage.

**Workaround:**

A possible workaround for this issue is to create an extra virtual server and an iRule: HSL pool targets 255.255.255.254:6514 -> VS (255.255.255.254:6514) with an iRule that has a CLIENT_ACCEPTED event with a single command “node 127.0.0.1 6514” to get the packet(s) to loopback.

**Comment by jsevedge** [comment]
This known issue is resolved in TS 1.2, docs now describe using an internal virtual server + iRule or tmm ipv6 link-local address (for per-app VE license constraint concerns): https://cloudsolutions.pages.gitswarm.f5net.com/f5-telemetry/userguide/event-listener.html#configure-the-log-publisher-using-tmsh

**Comment by asubmani** [comment]
> This known issue is resolved in TS 1.2, docs now describe using an internal virtual server + iRule or tmm ipv6 link-local address (for per-app VE license constraint concerns): https://cloudsolutions.pages.gitswarm.f5net.com/f5-telemetry/userguide/event-listener.html#configure-the-log-publisher-using-tmsh

The above url is not working..apparently this is still an issue with TS 1.4 where can I find the steps that describe how to use an internal virtual Server + iRule if I have single IP for my F5 (which is backed by an Axure Load balancer)

**Comment by kaustriaf5** [comment]
Please see latest:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html?highlight=log%20publisher#initial-configuration-for-a-standard-big-ip-system
